---
title: Opshopify
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: 
baseurl: "/opshopify"
stores:
- name: Joondalup
  address: 123 Fake Street Joondalup
  tags:
  - stylish
  - fun
  - cheap
- name: North Perth
  address: 432 Real Street North Perth
  tags:
  - edgy
  - cool
  - expensive
products:
- title: An ancient heirloom
  image: https://placehold.it/350x150
  price: "$2"
  store: Joondalup
- title: A nice dress
  image: https://placehold.it/350x150
  price: "$3"
  store: North Perth
- title: Culturally significant spears
  image: https://placehold.it/350x150
  price: "$10"
  store: Maddington
