---
title: Opshopify
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: 
baseurl: 
stores:
- name: Kelmscott
  address: 1/227 Railway Avenue Kelmscott WA 6111
  image: "/uploads/kelmscott.PNG"
  tags:
  - stylish
  - fun
  - cheap
- name: North Perth
  address: 392 Fitzgerald Street North Perth WA  6006
  image: "/uploads/north%20perth-191eb0.PNG"
  tags:
  - vintage
  - high end
  - quirky
  - collectors
- name: Belmont
  address: 9/199 Abernethy Road Belmont WA 6104
  image: "/uploads/belmont.PNG"
  tags:
  - clothes
  - white goods
- name: Fremantle
  address: Shop 1 142 High Street Fremantle WA 6160
  image: "/uploads/Fremantle.PNG"
  tags:
  - furniture
  - clothes
  - trinkets
- name: Maddington
  address: 2/3 Maddington Square 80 Attfield Street Maddington WA 6109
  image: "/uploads/Maddington.PNG"
  tags:
  - clothes
  - white goods
- name: Morley
  address: 4/129 Russell Street Morley WA 6062
  image: "/uploads/Morley.PNG"
  tags:
  - clothes
  - white goods
- name: Armadale
  address: Shop 2 Jull Street Armadale WA 6112
  image: "/uploads/Armadale.PNG"
  Key: Not the actual store but could be a way to attract people to the store
  tags:
  - clothes
  - white goods
products:
- title: An ancient heirloom
  name: heirloom
  image: "/uploads/tee-2122083_640.jpg"
  price: "$2"
  store: Joondalup
- title: Rock flavoured vase
  name: rockvase
  image: "/uploads/spring-2087435_640.jpg"
  price: "$20"
  store: Belmont
- title: A nice dress
  name: dress
  image: "/uploads/girl-1467456_640.jpg"
  price: "$3"
  store: North Perth
- title: Culturally significant spears
  name: spears
  image: "/uploads/don-quixote-1730269_640.jpg"
  price: "$10"
  store: Maddington
- title: Warm Jacket
  name: jacket
  image: "/uploads/man-1888335_640.jpg"
  price: "$20"
  store: North Perth
- title: Boomerang
  name: boomerang
  image: "/uploads/boomerang-1617503_640.jpg"
  price: "$5"
  store: Fremantle
- title: Diary
  name: diary
  image: "/uploads/notebook-1939358_640.jpg"
  price: "$5"
  store: Belmont
- title: Playing Cards
  name: playingcards
  image: "/uploads/playing-cards-1776279_640.jpg"
  price: "$2"
  store: Armadale
pcategories:
- name: Antiques
  products:
  - heirloom
  - spears
  - boomerang
  - rockvase
- name: Clothes
  products:
  - dress
  - jacket
- name: Toys
  products:
  - playingcards
- name: White Goods
  products:
  - diary
