---
title: Opshopify
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: 
baseurl: ''
stores:
- name: Joondalup
  address: 123 Fake Street Joondalup
  image: https://placehold.it/350x150
  tags:
  - stylish
  - fun
  - cheap
- name: North Perth
  address: 432 Real Street North Perth
  image: https://placehold.it/350x150
  tags:
  - edgy
  - cool
  - expensive
products:
- title: An ancient heirloom
  name: heirloom
  image: https://placehold.it/350x150
  price: "$2"
  store: Joondalup
- title: A nice dress
  name: dress
  image: https://placehold.it/350x150
  price: "$3"
  store: North Perth
- title: Culturally significant spears
  name: spears
  image: https://placehold.it/350x150
  price: "$10"
  store: Maddington
pcategories:
- name: Antiques
  products:
  - heirloom
  - spears
- name: Clothes
  products:
  - dress
