---
title: Opshopify
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  pages:
    title: Pages
    output: true
description: 
baseurl: 

products:
  - title: An ancient heirloom
    image:
    price: $2
    store: Joondalup
  - title: A nice dress
    image:
    price: $3
    store: North Perth
  - title: Culturally significant spears
    image:
    price: $10
    store: Maddington